name: Build RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-version: [ "8.1.3", "8.2.0" ]
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy ${{ matrix.renpy-version }}
      uses: PaxlavaGames/renpy-install@v0.3.0
      with:
        version: ${{ matrix.renpy-version }}
    - name: Build RenPy
      uses: PaxlavaGames/renpy-build@main
      with:
        path: "./testing"
    - name: Check results
      run: |
        echo "root folder..."
        ls
        echo "build folder..."
        ls ./build
